name: Semgrep

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 15 6 * * *
  workflow_dispatch:

env:
  CI: true
  FORCE_COLOR: 1
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  PYTHON_VERSION: "3.12"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          python -m pip install -U pip uv

      - name: Install semgrep
        run: |
          uv pip install --system semgrep

      - uses: 1password/load-secrets-action@v2
        id: op-load-secret
        with:
          export-env: true
        env:
          SEMGREP_APP_TOKEN: "op://GitHub Actions/SEMGREP_APP_TOKEN/credential"

      - run: |
          semgrep ci
